PARAM ball.model
END
GROUP 0 1
GROUP 0 8
TRANS  5.0   5.0   5.0
INPUT cube0.in.dat
SPINZ 180.0
TRANS -5.0   5.0   5.0
INPUT cube0.in.dat
SPINZ 180.0
TRANS -5.0  -5.0   5.0
INPUT cube0.in.dat
SPINY 180.0
TRANS -5.0  -5.0  -5.0
INPUT cube0.in.dat
SPINY 180.0
TRANS -5.0   5.0  -5.0
INPUT cube0.in.dat
SPINX 180.0
TRANS  5.0   5.0  -5.0
INPUT cube0.in.dat
SPINX 180.0
TRANS  5.0  -5.0  -5.0
INPUT cube0.in.dat
TRANS  5.0  -5.0   5.0
INPUT cube0.in.dat
